app = "sa-scheduler"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_URLS = "http://0.0.0.0:8080"
  ConnectionStrings__DefaultConnection = "Host=db.anebyqfrzsuqwrbncwxt.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=bunch-hiccups-misery-extreme;SSL Mode=Require;Trust Server Certificate=true"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "requests"

  [[services.http_checks]]
    interval = "15s"
    timeout = "3s"
    grace_period = "20s"
    method = "get"
    path = "/"
